/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_asanandroid_JniInterface */

#ifndef _Included_com_example_asanandroid_JniInterface
#define _Included_com_example_asanandroid_JniInterface
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_asanandroid_JniInterface
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT int JNICALL Java_com_example_asanandroid_JniInterface_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
